In [47]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from astropy import units as u
from astropy import constants as const

In [48]:
df = pd.read_csv("../../course_assignments/homework9/solar_system.csv")
df_original = df.copy()
df_original

,Attribute,Mercury,Venus,Earth,Moon,Mars,Jupiter,Saturn,Uranus,Neptune,Pluto
0,Mass (10^24kg),0.330,4.87,5.97,0.073,0.642,1898,568,86.8,102,0.0130
1,Diameter (km),4879,12104,12756,3475,6792,142984,120536,51118,49528,2376
2,Density (kg/m^3),5429,5243,5514,3340,3934,1326,687,1270,1638,1850
3,Gravity (m/s^2),3.7,8.9,9.8,1.6,3.7,23.1,9.0,8.7,11.0,0.7
4,Escape Velocity (km/s),4.3,10.4,11.2,2.4,5.0,59.5,35.5,21.3,23.5,1.3
5,Rotation Period (hours),1407.6,-5832.5,23.9,655.7,24.6,9.9,10.7,-17.2,16.1,-153.3
6,Length of Day (hours),4222.6,2802.0,24.0,708.7,24.7,9.9,10.7,17.2,16.1,153.3
7,Distance from Sun (10^6 km),57.9,108.2,149.6,0.384,228.0,778.5,1432.0,2867.0,4515.0,5906.4
8,Perihelion (10^6 km),46.0,107.5,147.1,0.363,206.7,740.6,1357.6,2732.7,4471.1,4436.8
9,Aphelion (10^6 km),69.8,108.9,152.1,0.406,249.3,816.4,1506.5,3001.4,4558.9,7375.9
10,Orbital Period (days),88.0,224.7,365.2,27.3,687.0,4331,10747,30589,59800,90560
11,Orbital Velocity (km/s),47.4,35.0,29.8,1.0,24.1,13.1,9.7,6.8,5.4,4.7
12,Orbital Inclination (deg),7.0,3.4,0.0,5.1,1.8,1.3,2.5,0.8,1.8,17.2
13,Orbital Eccentricity,0.206,0.007,0.017,0.055,0.094,0.049,0.052,0.047,0.010,0.244
14,Obliquity to Orbit (deg),0.034,177.4,23.4,6.7,25.2,3.1,26.7,97.8,28.3,119.5
15,Mean Temperature (C),167,464,15,-20,-65,-110,-140,-195,-200,-225
16,Surface Pressure (bars),0,92,1,0,0.01,Unknown,Unknown,Unknown,Unknown,0.00001
17,Number of Moons,0,0,1,0,2,95,274,28,16,5
18,Ring System?,No,No,No,No,No,Yes,Yes,Yes,Yes,No
19,Global Magnetic Field?,Yes,No,Yes,No,No,Yes,Yes,Yes,Yes,Unknown

In [49]:
df = df.set_index("Attribute").T
df.index.name = "Planet"
df.reset_index(inplace=True)
df.columns.name = None
df

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),Perihelion (10^6 km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3,1407.6,4222.6,57.9,46.0,...,88.0,47.4,7.0,0.206,0.034,167,0,0,No,Yes
1,Venus,4.87,12104,5243,8.9,10.4,-5832.5,2802.0,108.2,107.5,...,224.7,35.0,3.4,0.007,177.4,464,92,0,No,No
2,Earth,5.97,12756,5514,9.8,11.2,23.9,24.0,149.6,147.1,...,365.2,29.8,0.0,0.017,23.4,15,1,1,No,Yes
3,Moon,0.073,3475,3340,1.6,2.4,655.7,708.7,0.384,0.363,...,27.3,1.0,5.1,0.055,6.7,-20,0,0,No,No
4,Mars,0.642,6792,3934,3.7,5.0,24.6,24.7,228.0,206.7,...,687.0,24.1,1.8,0.094,25.2,-65,0.01,2,No,No
5,Jupiter,1898,142984,1326,23.1,59.5,9.9,9.9,778.5,740.6,...,4331,13.1,1.3,0.049,3.1,-110,Unknown,95,Yes,Yes
6,Saturn,568,120536,687,9.0,35.5,10.7,10.7,1432.0,1357.6,...,10747,9.7,2.5,0.052,26.7,-140,Unknown,274,Yes,Yes
7,Uranus,86.8,51118,1270,8.7,21.3,-17.2,17.2,2867.0,2732.7,...,30589,6.8,0.8,0.047,97.8,-195,Unknown,28,Yes,Yes
8,Neptune,102,49528,1638,11.0,23.5,16.1,16.1,4515.0,4471.1,...,59800,5.4,1.8,0.010,28.3,-200,Unknown,16,Yes,Yes
9,Pluto,0.0130,2376,1850,0.7,1.3,-153.3,153.3,5906.4,4436.8,...,90560,4.7,17.2,0.244,119.5,-225,0.00001,5,No,Unknown

In [50]:
# 5a
print("Shape BEFORE transpose:", df_original.shape)
print("Shape AFTER transpose:", df.shape)

# 5b
print("Rows BEFORE:", df_original.shape[0], " Columns BEFORE:", df_original.shape[1])
print("Rows AFTER:", df.shape[0], " Columns AFTER:", df.shape[1])

# 5c
# df = df.set_index('Attribute').T - Makes 'Attribute' the index, then transposes rows to columns
# df.index.name = 'Planet' - Names the new index
# df.reset_index(inplace=True) - Converts index back into a column called 'Planet'
# df.columns.name = None - Removes column index name

# 5d
# the original file does not have 11 clean attribute rows × 20 planet columns, some rows are labels or contain non-uniform structure, so the transpose does not create a perfect 11×20 grid

# 5e
print(list(df.columns))

# 5f
# columns with units: 16
# Mass (10^24kg)
# Diameter (km)
# Density (kg/m^3)
# Gravity (m/s^2)
# Escape Velocity (km/s)
# Rotation Period (hours)
# Length of Day (hours)
# Distance from Sun (10^6 km)
# Perihelion (10^6 km)
# Aphelion (10^6 km)
# Orbital Period (days)
# Orbital Velocity (km/s)
# Orbital Inclination (deg)
# Obliquity to Orbit (deg)
# Mean Temperature (C)
# Surface Pressure (bars)

# columns without units: 4
# Orbital Eccentricity
# Number of Moons
# Ring System?
# Global Magnetic Field?

# 5g
print(df)

Shape BEFORE transpose: (20, 11)
Shape AFTER transpose: (10, 21)
Rows BEFORE: 20  Columns BEFORE: 11
Rows AFTER: 10  Columns AFTER: 21
['Planet', 'Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)', 'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)', 'Length of Day (hours)', 'Distance from Sun (10^6 km)', 'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'Orbital Period (days)', 'Orbital Velocity (km/s)', 'Orbital Inclination (deg)', 'Orbital Eccentricity', 'Obliquity to Orbit (deg)', 'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons', 'Ring System?', 'Global Magnetic Field?']
    Planet Mass (10^24kg) Diameter (km) Density (kg/m^3) Gravity (m/s^2)  \
0  Mercury          0.330          4879             5429             3.7
1    Venus           4.87         12104             5243             8.9
2    Earth           5.97         12756             5514             9.8
3     Moon          0.073          3475             3340             1.6
4     Mars          0.642          6792             3934             3.7
5  Jupiter           1898        142984             1326            23.1
6   Saturn            568        120536              687             9.0
7   Uranus           86.8         51118             1270             8.7
8  Neptune            102         49528             1638            11.0
9    Pluto         0.0130          2376             1850             0.7

  Escape Velocity (km/s) Rotation Period (hours) Length of Day (hours)  \
0                    4.3                  1407.6                4222.6
1                   10.4                 -5832.5                2802.0
2                   11.2                    23.9                  24.0
3                    2.4                   655.7                 708.7
4                    5.0                    24.6                  24.7
5                   59.5                     9.9                   9.9
6                   35.5                    10.7                  10.7
7                   21.3                   -17.2                  17.2
8                   23.5                    16.1                  16.1
9                    1.3                  -153.3                 153.3

  Distance from Sun (10^6 km) Perihelion (10^6 km)  ... Orbital Period (days)  \
0                        57.9                 46.0  ...                  88.0
1                       108.2                107.5  ...                 224.7
2                       149.6                147.1  ...                 365.2
3                       0.384                0.363  ...                  27.3
4                       228.0                206.7  ...                 687.0
5                       778.5                740.6  ...                  4331
6                      1432.0               1357.6  ...                 10747
7                      2867.0               2732.7  ...                 30589
8                      4515.0               4471.1  ...                 59800
9                      5906.4               4436.8  ...                 90560

  Orbital Velocity (km/s) Orbital Inclination (deg) Orbital Eccentricity  \
0                    47.4                       7.0                0.206
1                    35.0                       3.4                0.007
2                    29.8                       0.0                0.017
3                     1.0                       5.1                0.055
4                    24.1                       1.8                0.094
5                    13.1                       1.3                0.049
6                     9.7                       2.5                0.052
7                     6.8                       0.8                0.047
8                     5.4                       1.8                0.010
9                     4.7                      17.2                0.244

  Obliquity to Orbit (deg) Mean Temperature (C) Surface Pressure (bars)  \
0                    0.034                  167                       0
1                    177.4                  464                      92
2                     23.4                   15                       1
3                      6.7                  -20                       0
4                     25.2                  -65                    0.01
5                      3.1                 -110                 Unknown
6                     26.7                 -140                 Unknown
7                     97.8                 -195                 Unknown
8                     28.3                 -200                 Unknown
9                    119.5                 -225                 0.00001

  Number of Moons Ring System? Global Magnetic Field?
0               0           No                    Yes
1               0           No                     No
2               1           No                    Yes
3               0           No                     No
4               2           No                     No
5              95          Yes                    Yes
6             274          Yes                    Yes
7              28          Yes                    Yes
8              16          Yes                    Yes
9               5           No                Unknown

[10 rows x 21 columns]

In [51]:
df.dtypes

Planet                         object
Mass (10^24kg)                 object
Diameter (km)                  object
Density (kg/m^3)               object
Gravity (m/s^2)                object
Escape Velocity (km/s)         object
Rotation Period (hours)        object
Length of Day (hours)          object
Distance from Sun (10^6 km)    object
Perihelion (10^6 km)           object
Aphelion (10^6 km)             object
Orbital Period (days)          object
Orbital Velocity (km/s)        object
Orbital Inclination (deg)      object
Orbital Eccentricity           object
Obliquity to Orbit (deg)       object
Mean Temperature (C)           object
Surface Pressure (bars)        object
Number of Moons                object
Ring System?                   object
Global Magnetic Field?         object
dtype: object

In [52]:
for col in df.columns:
    print(col, df[col].apply(type).unique())

Planet [<class 'str'>]
Mass (10^24kg) [<class 'str'>]
Diameter (km) [<class 'str'>]
Density (kg/m^3) [<class 'str'>]
Gravity (m/s^2) [<class 'str'>]
Escape Velocity (km/s) [<class 'str'>]
Rotation Period (hours) [<class 'str'>]
Length of Day (hours) [<class 'str'>]
Distance from Sun (10^6 km) [<class 'str'>]
Perihelion (10^6 km) [<class 'str'>]
Aphelion (10^6 km) [<class 'str'>]
Orbital Period (days) [<class 'str'>]
Orbital Velocity (km/s) [<class 'str'>]
Orbital Inclination (deg) [<class 'str'>]
Orbital Eccentricity [<class 'str'>]
Obliquity to Orbit (deg) [<class 'str'>]
Mean Temperature (C) [<class 'str'>]
Surface Pressure (bars) [<class 'str'>]
Number of Moons [<class 'str'>]
Ring System? [<class 'str'>]
Global Magnetic Field? [<class 'str'>]

In [53]:
# 2.1.2
# 3a
# They are strings.

# 3b
# It is a problem since you cannot perform mathematical operations on strings.

In [54]:
# 2.1.3
exclude = ["Planet", "Ring System?", "Global Magnetic Field?"]

cols_to_convert = [col for col in df.columns if col not in exclude]

for col in cols_to_convert:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df.dtypes

# a)
# float64, int64 and object

# b)
# float64: 64-bit floating-point number
# int64: 64-bit integer
# object: Generic object type, cannot be expressed as number

# c)
# "Planet", "Ring System?" and "Global Magnetic Field?" are still objects since they contain text labels and not numbers

Planet                          object
Mass (10^24kg)                 float64
Diameter (km)                    int64
Density (kg/m^3)                 int64
Gravity (m/s^2)                float64
Escape Velocity (km/s)         float64
Rotation Period (hours)        float64
Length of Day (hours)          float64
Distance from Sun (10^6 km)    float64
Perihelion (10^6 km)           float64
Aphelion (10^6 km)             float64
Orbital Period (days)          float64
Orbital Velocity (km/s)        float64
Orbital Inclination (deg)      float64
Orbital Eccentricity           float64
Obliquity to Orbit (deg)       float64
Mean Temperature (C)             int64
Surface Pressure (bars)        float64
Number of Moons                  int64
Ring System?                    object
Global Magnetic Field?          object
dtype: object

In [55]:
def attach_units(col_name, unit, new_col_name=None):
        df[col_name] = df[col_name].apply(lambda x: x * unit)
    
        if new_col_name is not None:
            df.rename(columns={col_name: new_col_name}, inplace=True)

attach_units(
    col_name="Mass (10^24kg)",
    unit=(1e24 * u.kg),
    new_col_name="Mass (kg)"
)

print(df["Mass (kg)"])

0                   3.3e+23 kg
1                  4.87e+24 kg
2     5.969999999999999e+24 kg
3                   7.3e+22 kg
4                  6.42e+23 kg
5                 1.898e+27 kg
6                  5.68e+26 kg
7                  8.68e+25 kg
8    1.0199999999999999e+26 kg
9                   1.3e+22 kg
Name: Mass (kg), dtype: object

In [57]:


# Compute semi-major axis = average of perihelion + aphelion
semi_major_axis = (df["Perihelion (10^6 km)"] + df["Aphelion (10^6 km)"]) / 2

# Attach units: values are in (10^6 km)
semi_major_axis = semi_major_axis * 1e6 * u.km

# Insert new column RIGHT AFTER Aphelion (which is index 9)
df.insert(
    loc=df.columns.get_loc("Aphelion (10^6 km)") + 1,
    column="Semi-Major Axis (km)",
    value=semi_major_axis
)

# Print all column names to confirm insertion
print("\nCOLUMN NAMES AFTER INSERTING SEMI-MAJOR AXIS:")
print(df.columns)

# Print the new column
print("\nSemi-Major Axis Column (with units):")
print(df["Semi-Major Axis (km)"])


# -----------------------------
# 2.3.2  ORBITAL PERIOD → YEARS
# -----------------------------

# Convert from days to years using Astropy

orbital_period_years = (df["Orbital Period (days)"].values * u.day).to(u.year)

# Assign back to DataFrame
df["Orbital Period (yr)"] = orbital_period_years

# Rename the column
df.rename(columns={"Orbital Period (days)": "Orbital Period (yr)"}, inplace=True)

# Print column names
print("\nCOLUMN NAMES AFTER RENAMING ORBITAL PERIOD:")
print(df.columns)

# Print the full column
print("\nOrbital Period (yr):")
print(df["Orbital Period (yr)"])

# Print your favorite planet’s orbital period
favorite = "Earth"    # ← CHANGE IF YOU WANT A DIFFERENT PLANET
value = df.loc[df["Planet"] == favorite, "Orbital Period (yr)"].iloc[0]
print(f"\n{favorite}'s orbital period in years: {value:.4f}")


# -----------------------------
# 2.3.3  DISTANCE (km → AU)
# -----------------------------

# Define: What is 1 AU?
print("\nDEFINITION:")
print("One Astronomical Unit (AU) is the average distance from the Earth to the Sun.")

# Print 1 AU (astropy)
print("\n1 AU with Astropy:")
print(const.au)

# How many kilometers is 1 AU?
print("\nKilometers in 1 AU:")
print(const.au.to(u.km))

# Columns to convert (all are in km or 10^6 km)
distance_cols = [
    "Diameter (km)",
    "Distance from Sun (10^6 km)",
    "Perihelion (10^6 km)",
    "Aphelion (10^6 km)",
    "Semi-Major Axis (km)"
]

# Convert each column to AU
for col in distance_cols:

    # Get numerical values (some columns are in 10^6 km, so scale them)
    if "10^6" in col:
        values_km = df[col] * 1e6 * u.km
    else:
        values_km = df[col] * u.km

    # Convert to AU
    values_au = values_km.to(u.AU)

    # Build new name
    new_name = col.replace("(km)", "(AU)").replace("(10^6 km)", "(AU)")

    # Store back in DataFrame
    df[col] = values_au
    df.rename(columns={col: new_name}, inplace=True)

# Print sample values for your favorite planet
print(f"\nDistance column samples for {favorite}:")
for col in df.columns:
    if "(AU)" in col:
        val = df.loc[df["Planet"] == favorite, col].iloc[0]
        print(f"{col}: {val}")

ValueError: cannot insert Semi-Major Axis (km), already exists